# -*- coding: utf-8 -*-
"""ProgIIIG1-202502-Sudoku.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t3xjTX2AMtHjZ3_EeUzZal8gugt8IZcI
"""

cols="ABCDEFGHI"
# var_doms={letra:set(range(10)) for letra in set(cols)}
import itertools as it
keys=list(it.product(range(1,10),cols))
strKeys=[f"{key[1]}{key[0]}" for key in keys]
var_doms={key:set(range(1,10)) for key in strKeys}

#boardname="SD1EBVCL_muyfacil"
boardname="board"
with open(boardname, 'r') as f:
  for key in var_doms.keys():
    valor=f.readline().strip()
    if valor.isdigit() and len(valor) == 1:  # Verifica si es un solo dígito
      #print(f"{key}={valor}")
      var_doms[key]={int(valor)}

def DefRowsConstraints(cols,rows):
  RowsConstraints=[]
  for i in rows:
    ConstraintVars=[f"{id}{i}" for id in cols]
    RowsConstraints.append(ConstraintVars)
    #print(ConstraintVars)
  return RowsConstraints

def DefColsConstraints(cols,rows):
  ColsConstraints=[]
  for id in cols:
    ConstraintVars=[f"{id}{i}" for i in rows]
    ColsConstraints.append(ConstraintVars)
    #print(ConstraintVars)
  return ColsConstraints

#define boxes for sudoku board
def DefBoxesConstraints(cols,rows):
  BoxesConstraints=[]
  for i in range(3):
    for j in range(3):
      ConstraintVars=[]
      for x in range(3):
        for y in range(3):
          ConstraintVars.append(f"{cols[i*3+x]}{rows[j*3+y]}")
      BoxesConstraints.append(ConstraintVars)
      #print(ConstraintVars)
  return BoxesConstraints

def AllDif(var_doms,vars):
  anyChange=False
  for var in vars:
    if len(var_doms[var])==1:
      for var2 in vars:
        if var!=var2:
          #if var_doms[var].issubset(var_doms[var2]):
          #  anyChange=True
          if list(var_doms[var])[0] in var_doms[var2]:
            anyChange=True
          var_doms[var2].discard(list(var_doms[var])[0])
  return anyChange

def ExcValue(var_doms,vars):
  anyChange=False
  for var in vars:
    if len(var_doms[var])>1:
      A=var_doms[var]
      U=set()
      for var2 in vars:
        if var!=var2:
          if len(var_doms[var2])>1:
            U=U.union(var_doms[var2])
      Ex=A-U
      if len(Ex)==1:
        var_doms[var]=Ex
        anyChange=True
  return anyChange

DefRowsConstraints(cols,range(1,10))

DefColsConstraints(cols,range(1,10))

DefBoxesConstraints(cols,range(1,10))

varsGroups=DefRowsConstraints(cols,range(1,10))+DefColsConstraints(cols,range(1,10))+DefBoxesConstraints(cols,range(1,10))
#for vars in varsGroups:
#  AllDif(var_doms,vars)
#var_doms

constraints=[]
for group in varsGroups:
  constraints.append(('AllDif',group))
  constraints.append(('ExcValue',group))


iteration=1
while(True):
  anyChange=False
  for constraint in constraints:
    anyChangeAux=eval(f"{constraint[0]}(var_doms,{constraint[1]})")
    anyChange=anyChangeAux if anyChange==False else anyChange
  print(f"Iteracion {iteration}")
  iteration+=1
  #input()
  if anyChange==False:
    break

eval(f"{constraints[0][0]}(var_doms,{constraints[0][1]})")

#despues de anyChange

print(var_doms)

A={1,3,7}
U={1,3,4,5}
Ex=A-U
Ex